// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type ArrayDefs struct {
	// MyInlineTags corresponds to the JSON schema field "myInlineTags".
	MyInlineTags []string `json:"myInlineTags,omitempty,omitzero" yaml:"myInlineTags,omitempty" mapstructure:"myInlineTags,omitempty"`

	// MyNumbers corresponds to the JSON schema field "myNumbers".
	MyNumbers AtLeastOne `json:"myNumbers,omitempty,omitzero" yaml:"myNumbers,omitempty" mapstructure:"myNumbers,omitempty"`

	// MyPair corresponds to the JSON schema field "myPair".
	MyPair AtMostTwo `json:"myPair,omitempty,omitzero" yaml:"myPair,omitempty" mapstructure:"myPair,omitempty"`

	// MyTags corresponds to the JSON schema field "myTags".
	MyTags Tags `json:"myTags" yaml:"myTags" mapstructure:"myTags"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ArrayDefs) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw ArrayDefs: %w", err)
	}
	if _, ok := raw["myTags"]; raw != nil && !ok {
		return fmt.Errorf("field myTags in ArrayDefs: required")
	}
	type Plain ArrayDefs
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal ArrayDefs: %w", err)
	}
	if plain.MyInlineTags != nil && len(plain.MyInlineTags) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "myInlineTags", 2)
	}
	*j = ArrayDefs(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *ArrayDefs) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw ArrayDefs: %w", err)
	}
	if _, ok := raw["myTags"]; raw != nil && !ok {
		return fmt.Errorf("field myTags in ArrayDefs: required")
	}
	type Plain ArrayDefs
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal ArrayDefs: %w", err)
	}
	if plain.MyInlineTags != nil && len(plain.MyInlineTags) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "myInlineTags", 2)
	}
	*j = ArrayDefs(plain)
	return nil
}

type AtLeastOne []int

// UnmarshalJSON implements json.Unmarshaler.
func (j *AtLeastOne) UnmarshalJSON(value []byte) error {
	type Plain AtLeastOne
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal AtLeastOne: %w", err)
	}
	if plain != nil && len(plain) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "AtLeastOne", 1)
	}
	*j = AtLeastOne(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AtLeastOne) UnmarshalYAML(value *yaml.Node) error {
	type Plain AtLeastOne
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal AtLeastOne: %w", err)
	}
	if plain != nil && len(plain) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "AtLeastOne", 1)
	}
	*j = AtLeastOne(plain)
	return nil
}

type AtMostTwo []string

// UnmarshalJSON implements json.Unmarshaler.
func (j *AtMostTwo) UnmarshalJSON(value []byte) error {
	type Plain AtMostTwo
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal AtMostTwo: %w", err)
	}
	if len(plain) > 2 {
		return fmt.Errorf("field %s length: must be <= %d", "AtMostTwo", 2)
	}
	*j = AtMostTwo(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AtMostTwo) UnmarshalYAML(value *yaml.Node) error {
	type Plain AtMostTwo
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal AtMostTwo: %w", err)
	}
	if len(plain) > 2 {
		return fmt.Errorf("field %s length: must be <= %d", "AtMostTwo", 2)
	}
	*j = AtMostTwo(plain)
	return nil
}

type Tags []string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Tags) UnmarshalJSON(value []byte) error {
	type Plain Tags
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal Tags: %w", err)
	}
	if plain != nil && len(plain) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "Tags", 2)
	}
	if len(plain) > 3 {
		return fmt.Errorf("field %s length: must be <= %d", "Tags", 3)
	}
	*j = Tags(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *Tags) UnmarshalYAML(value *yaml.Node) error {
	type Plain Tags
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal Tags: %w", err)
	}
	if plain != nil && len(plain) < 2 {
		return fmt.Errorf("field %s length: must be >= %d", "Tags", 2)
	}
	if len(plain) > 3 {
		return fmt.Errorf("field %s length: must be <= %d", "Tags", 3)
	}
	*j = Tags(plain)
	return nil
}
