// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "strings"

// A property named "-" beside typed additionalProperties. Once the decoder binds
// "-" to its field, the generated pruning must treat it as a declared key, or its
// value is copied into the catch-all map as well.
type DashPropertyNameAdditional struct {
	// Dash corresponds to the JSON schema field "-".
	Dash string `json:"-," yaml:"-" mapstructure:"-"`

	AdditionalProperties map[string]string `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DashPropertyNameAdditional) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw DashPropertyNameAdditional: %w", err)
	}
	if _, ok := raw["-"]; raw != nil && !ok {
		return fmt.Errorf("field - in DashPropertyNameAdditional: required")
	}
	type Plain DashPropertyNameAdditional
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal DashPropertyNameAdditional: %w", err)
	}
	if v, ok := raw[""]; !ok || v == nil {
		plain.AdditionalProperties = map[string]string{}
	}
	st := reflect.TypeOf(Plain{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if f.Name == "AdditionalProperties" {
			continue
		}
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name := strings.Split(tag, ",")[0]
		if name == "" {
			name = f.Name
		}
		for k := range raw {
			if strings.EqualFold(k, name) {
				delete(raw, k)
			}
		}
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return fmt.Errorf("decode additional properties for DashPropertyNameAdditional: %w", err)
	}
	*j = DashPropertyNameAdditional(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *DashPropertyNameAdditional) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw DashPropertyNameAdditional: %w", err)
	}
	if _, ok := raw["-"]; raw != nil && !ok {
		return fmt.Errorf("field - in DashPropertyNameAdditional: required")
	}
	type Plain DashPropertyNameAdditional
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal DashPropertyNameAdditional: %w", err)
	}
	if v, ok := raw[""]; !ok || v == nil {
		plain.AdditionalProperties = map[string]string{}
	}
	st := reflect.TypeOf(Plain{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if f.Name == "AdditionalProperties" {
			continue
		}
		tag := f.Tag.Get("yaml")
		if tag == "-" {
			continue
		}
		name := strings.Split(tag, ",")[0]
		if name == "" {
			name = strings.ToLower(f.Name)
		}
		for k := range raw {
			if k == name {
				delete(raw, k)
			}
		}
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return fmt.Errorf("decode additional properties for DashPropertyNameAdditional: %w", err)
	}
	*j = DashPropertyNameAdditional(plain)
	return nil
}
