// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import yaml "gopkg.in/yaml.v3"

// A property literally named "-". encoding/json reads a tag of exactly "-" as
// "always omit this field", so the name needs the trailing comma the package
// documents for that case to stay a key.
type DashPropertyName struct {
	// Dash corresponds to the JSON schema field "-".
	Dash string `json:"-," yaml:"-" mapstructure:"-"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *DashPropertyName) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw DashPropertyName: %w", err)
	}
	if _, ok := raw["-"]; raw != nil && !ok {
		return fmt.Errorf("field - in DashPropertyName: required")
	}
	type Plain DashPropertyName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal DashPropertyName: %w", err)
	}
	*j = DashPropertyName(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *DashPropertyName) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw DashPropertyName: %w", err)
	}
	if _, ok := raw["-"]; raw != nil && !ok {
		return fmt.Errorf("field - in DashPropertyName: required")
	}
	type Plain DashPropertyName
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal DashPropertyName: %w", err)
	}
	*j = DashPropertyName(plain)
	return nil
}
