// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import yaml "gopkg.in/yaml.v3"
import "reflect"
import "strings"

type StringAdditionalProperties struct {
	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	AdditionalProperties map[string]string `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *StringAdditionalProperties) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return fmt.Errorf("unmarshal raw StringAdditionalProperties: %w", err)
	}
	type Plain StringAdditionalProperties
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return fmt.Errorf("unmarshal StringAdditionalProperties: %w", err)
	}
	if v, ok := raw[""]; !ok || v == nil {
		plain.AdditionalProperties = map[string]string{}
	}
	st := reflect.TypeOf(Plain{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if f.Name == "AdditionalProperties" {
			continue
		}
		tag := f.Tag.Get("json")
		if tag == "-" {
			continue
		}
		name := strings.Split(tag, ",")[0]
		if name == "" {
			name = f.Name
		}
		for k := range raw {
			if strings.EqualFold(k, name) {
				delete(raw, k)
			}
		}
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return fmt.Errorf("decode additional properties for StringAdditionalProperties: %w", err)
	}
	*j = StringAdditionalProperties(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *StringAdditionalProperties) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return fmt.Errorf("unmarshal raw StringAdditionalProperties: %w", err)
	}
	type Plain StringAdditionalProperties
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return fmt.Errorf("unmarshal StringAdditionalProperties: %w", err)
	}
	if v, ok := raw[""]; !ok || v == nil {
		plain.AdditionalProperties = map[string]string{}
	}
	st := reflect.TypeOf(Plain{})
	for i := 0; i < st.NumField(); i++ {
		f := st.Field(i)
		if f.Name == "AdditionalProperties" {
			continue
		}
		tag := f.Tag.Get("yaml")
		if tag == "-" {
			continue
		}
		name := strings.Split(tag, ",")[0]
		if name == "" {
			name = strings.ToLower(f.Name)
		}
		for k := range raw {
			if k == name {
				delete(raw, k)
			}
		}
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return fmt.Errorf("decode additional properties for StringAdditionalProperties: %w", err)
	}
	*j = StringAdditionalProperties(plain)
	return nil
}
