#!/usr/bin/env bash

# Rewrites the Go module path between upstream's and the fork's.
#
#   scripts/fork/rewrite-module-path.sh            github.com/atombender/... -> github.com/plheide/...
#   scripts/fork/rewrite-module-path.sh --reverse  github.com/plheide/... -> github.com/atombender/...
#
# The rewrite works line by line. A line carrying the generated-code header
# ("Code generated by ...") keeps upstream's path, so generated output and
# its golden files do not change. FORK.md and scripts/fork name both paths on
# purpose and are left alone. Untracked files are included, ignored ones are
# not. --reverse is for exporting a change from main to a branch based on
# upstream-main.

set -o errexit -o nounset -o pipefail

upstream=github.com/atombender/go-jsonschema
fork=github.com/plheide/go-jsonschema

from=${upstream}
to=${fork}

# Exactly no argument or --reverse: a mistyped flag must not run the rewrite
# in the other direction.
case "$#:${1:-}" in
  0:) ;;
  1:--reverse)
    from=${fork}
    to=${upstream}
    ;;
  *)
    echo "usage: scripts/fork/rewrite-module-path.sh [--reverse]" >&2
    exit 2
    ;;
esac

root=$(git rev-parse --show-toplevel)
cd "${root}"

exclude=(':(exclude)FORK.md' ':(exclude)scripts/fork')

# matches runs git grep over the tree, untracked files included. git grep
# exits 1 when nothing matches, which is not an error here; above 1 is.
matches() {
  local rc=0
  git grep --untracked "$@" -- . "${exclude[@]}" || rc=$?
  if ((rc > 1)); then
    return "${rc}"
  fi
}

# shellcheck disable=SC2016 # perl reads FROM and TO from its environment.
matches -lzF "${from}" |
  FROM=${from} TO=${to} xargs -0 -r perl -pi -e 's{\Q$ENV{FROM}\E}{$ENV{TO}}g unless /Code generated by/'

# Outside the generated-code header, nothing may still use the old path.
residue=$(matches -nF "${from}")
residue=$(grep -v 'Code generated by' <<< "${residue}" || true)

if [[ -n "${residue}" ]]; then
  echo "${residue}" >&2
  echo "rewrite-module-path: ${from} is still referenced above" >&2
  exit 1
fi
